FROM httpd:2.4
COPY my-httpd.conf /usr/local/apache2/conf/httpd.conf
COPY httpd-vhosts.conf /usr/local/apache2/conf/extra/
# COPY server.crt /usr/local/apache2/conf/server.crt
# COPY server.key /usr/local/apache2/conf/server.key

EXPOSE 80
EXPOSE 82
EXPOSE 443
